# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 278)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 10, 81, 16))
        self.label.setObjectName("label")
        self.generate_key = QtWidgets.QPushButton(self.centralwidget)
        self.generate_key.setGeometry(QtCore.QRect(50, 30, 75, 23))
        self.generate_key.setObjectName("generate_key")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 40, 61, 16))
        self.label_2.setObjectName("label_2")
        self.information = QtWidgets.QTextEdit(self.centralwidget)
        self.information.setGeometry(QtCore.QRect(230, 40, 361, 71))
        self.information.setObjectName("information")
        self.Sig = QtWidgets.QTextEdit(self.centralwidget)
        self.Sig.setGeometry(QtCore.QRect(230, 120, 361, 71))
        self.Sig.setObjectName("Sig")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 120, 47, 13))
        self.label_3.setObjectName("label_3")
        self.sig = QtWidgets.QPushButton(self.centralwidget)
        self.sig.setGeometry(QtCore.QRect(220, 200, 75, 23))
        self.sig.setObjectName("sig")
        self.verify = QtWidgets.QPushButton(self.centralwidget)
        self.verify.setGeometry(QtCore.QRect(460, 200, 75, 23))
        self.verify.setObjectName("verify")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ECC Cipher"))
        self.generate_key.setText(_translate("MainWindow", "Generate Key"))
        self.label_2.setText(_translate("MainWindow", "information"))
        self.label_3.setText(_translate("MainWindow", "Signature"))
        self.sig.setText(_translate("MainWindow", "Sign"))
        self.verify.setText(_translate("MainWindow", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
