# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 180, 61, 20))
        self.label_4.setObjectName("label_4")
        self.txt_info = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_info.setGeometry(QtCore.QRect(450, 70, 221, 71))
        self.txt_info.setObjectName("txt_info")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(390, 60, 61, 16))
        self.label_3.setObjectName("label_3")
        self.txt_plain_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_plain_text.setGeometry(QtCore.QRect(110, 70, 251, 71))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.txt_cipher_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_cipher_text.setGeometry(QtCore.QRect(110, 170, 251, 71))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 47, 13))
        self.label_2.setObjectName("label_2")
        self.Encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.Encrypt.setGeometry(QtCore.QRect(100, 280, 75, 23))
        self.Encrypt.setObjectName("Encrypt")
        self.Verivy = QtWidgets.QPushButton(self.centralwidget)
        self.Verivy.setGeometry(QtCore.QRect(560, 280, 75, 23))
        self.Verivy.setObjectName("Verivy")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(390, 180, 61, 20))
        self.label_5.setObjectName("label_5")
        self.Sign = QtWidgets.QPushButton(self.centralwidget)
        self.Sign.setGeometry(QtCore.QRect(460, 280, 75, 23))
        self.Sign.setObjectName("Sign")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 30, 71, 16))
        self.label.setObjectName("label")
        self.txt_sign = QtWidgets.QTextBrowser(self.centralwidget)
        self.txt_sign.setGeometry(QtCore.QRect(450, 170, 256, 71))
        self.txt_sign.setObjectName("txt_sign")
        self.Decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.Decrypt.setGeometry(QtCore.QRect(220, 280, 75, 23))
        self.Decrypt.setObjectName("Decrypt")
        self.GenKeys = QtWidgets.QPushButton(self.centralwidget)
        self.GenKeys.setGeometry(QtCore.QRect(40, 20, 75, 23))
        self.GenKeys.setObjectName("GenKeys")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Cipher text"))
        self.label_3.setText(_translate("MainWindow", "Infomation"))
        self.label_2.setText(_translate("MainWindow", "Plaint text"))
        self.Encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.Verivy.setText(_translate("MainWindow", "Verify"))
        self.label_5.setText(_translate("MainWindow", "Signature"))
        self.Sign.setText(_translate("MainWindow", "Sign"))
        self.label.setText(_translate("MainWindow", "RSA Cipher"))
        self.Decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.GenKeys.setText(_translate("MainWindow", "Generate Key"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
